name: go-webserver
summary: Lightweight webserver to display a basic html file
description: |
      Created to display a basic loading html file until the PLC has started.
adopt-info: go-webserver
base: core22

confinement: strict

plugs:

apps:
  go-webserver:
    command: bin/main
    plugs:
      - home

parts:
  go-webserver:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/jgrantmoore/go-webserver
    source-type: git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
      "$(git describe --long --tags --always --match=v*.*.* | sed 's/v//')"