name: go-webserver
summary: Lightweight webserver to display a basic html file
description: |
      Created to display a basic loading html file until the PLC has started.
adopt-info: go-webserver
base: core22
confinement: strict
type: app

apps:
  go-webserver:
    command: bin/main
    plugs:
      - home
      - browser-support
      - network
      - network-status
      - network-bind
      - network-observe
      - network-control
    daemon: simple
    restart-condition: always
parts:
  go-webserver:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/jgrantmoore/go-webserver
    source-type: git
    override-build: |
      go build -o ./bin/ main.go