name: go-webserver
summary: Lightweight webserver to display a basic html file
description: |
      Created to display a basic loading html file until the PLC has started.
version: test
base: core22
confinement: strict
grade: stable
type: app

apps:
  go-webserver:
    command: build/main
    plugs:
      - home
      - browser-support
      - network
      - network-bind
    daemon: simple
    restart-condition: always

parts:
  go-webserver:
    plugin: dump
    build-snaps: [go/latest/stable]
    source: ./build